---
- name: Managing the sl package
  hosts: all
  tasks:
  - name: Manage sl package on CentOS
    yum: 
      name: sl 
      state: "{{ package_state }}"
      update_cache: yes
    when: ansible_facts['os_family'] == "RedHat"

  - name: Manage sl package on Ubuntu
    apt: 
      pkg: sl 
      state: "{{ package_state }}"
      update_cache: yes
    when: ansible_facts['os_family'] == "Debian"
